### ISSUE TITLE
Local storage for avatar URL

### ISSUE THREAD

**Issue by ryanbliss** [mscherotter/galeryst#49]
**Is your feature request related to a problem? Please describe.**
There is a bit of friction in finding my avatar URL when choosing a new scene.

**Describe the solution you'd like**
Would be nice to have that saved in local storage so it is easy to find after initial use.

**Describe alternatives you've considered**
Any storage mechanism would be nice.

**Comment by corinagum** [comment]
Just to add on to this (I don't think it warrants an entire feature request) 

When I jumped into the app for the first time, it didn't register in my head that I was setting up a username/avatar that would be used in the gallery viewing. (maybe I missed a description because I jumped into the app without context)

But I would appreciate that the avatar/username modal to also show a description of what the user set up is for. 🙂
